services:
  - type: web
    name: tasty-cake-shop
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Content-Type
        value: text/html
      - path: /*.css
        name: Content-Type
        value: text/css
      - path: /*.js
        name: Content-Type
        value: application/javascript